gerrit:
  image: "dmlb2000/docker-gerrit"
  ports:
   - "8080:8080"
  volumes:
   - "./data:/data"
  links:
   - gerrit-mysql:mysql
   - gerrit-mail:mail
  privileged: true
  user: "1000"
gerrit-mysql:
  image: "mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "gerrit"
    MYSQL_USER: "gerrit"
    MYSQL_PASSWORD: "gerrit"
gerrit-mail:
  image: "dmlb2000/docker-postfix"
  environment:
    maildomain: mail.dmlb2000.org
    smtp_user: gerrit:gerrit
