gerrit:
  image: "dmlb2000/docker-gerrit"
  ports:
   - "8080:8080"
   - "29418:29418"
  volumes:
   - "./data:/data"
  links:
   - gerrit-mysql:mysql
   - gerrit-mail:mail
  privileged: true
  user: "1000"
  environment:
    GERRIT_PLUGINS: "https://gerrit-ci.gerritforge.com/job/plugin-github-mvn-stable-2.11/lastSuccessfulBuild/artifact/github-oauth/target/github-oauth-2.11.jar https://gerrit-ci.gerritforge.com/job/plugin-github-mvn-stable-2.11/lastSuccessfulBuild/artifact/github-plugin/target/github-plugin-2.11.jar"
gerrit-mysql:
  image: "mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "gerrit"
    MYSQL_USER: "gerrit"
    MYSQL_PASSWORD: "gerrit"
gerrit-mail:
  image: "dmlb2000/docker-postfix"
  environment:
    maildomain: mail.dmlb2000.org
    smtp_user: gerrit:gerrit
